import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTrades } from "../hooks/useMarketData";
export default function TradeJournal() {
    const { rows, refresh } = useTrades();
    return (_jsxs("div", { className: "bg-white rounded p-4 shadow", children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsx("h2", { className: "font-semibold", children: "Trade Journal" }), _jsx("button", { onClick: refresh, className: "px-3 py-1 text-sm bg-blue-600 text-white rounded", children: "Refresh" })] }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "min-w-full border-collapse border border-gray-300 text-sm", children: [_jsx("thead", { className: "bg-gray-100", children: _jsxs("tr", { children: [_jsx("th", { className: "border p-2", children: "#" }), _jsx("th", { className: "border p-2", children: "Symbol" }), _jsx("th", { className: "border p-2", children: "Side" }), _jsx("th", { className: "border p-2", children: "Qty" }), _jsx("th", { className: "border p-2", children: "Price" }), _jsx("th", { className: "border p-2", children: "Exchange" }), _jsx("th", { className: "border p-2", children: "Product" }), _jsx("th", { className: "border p-2", children: "Brokerage" }), _jsx("th", { className: "border p-2", children: "Net Amount" }), _jsx("th", { className: "border p-2", children: "Date" }), _jsx("th", { className: "border p-2", children: "Time" })] }) }), _jsx("tbody", { children: rows.map((t, i) => {
                                const meta = t.meta || {};
                                return (_jsxs("tr", { children: [_jsx("td", { className: "border p-2 text-center", children: i + 1 }), _jsx("td", { className: "border p-2", children: t.symbol || "-" }), _jsx("td", { className: "border p-2", children: t.side || "-" }), _jsx("td", { className: "border p-2 text-right", children: t.qty || 0 }), _jsxs("td", { className: "border p-2 text-right", children: ["\u20B9", t.price ? t.price.toFixed(2) : "0.00"] }), _jsx("td", { className: "border p-2", children: t.exchange || meta.Exch || "-" }), _jsx("td", { className: "border p-2", children: t.product || meta.Product || "-" }), _jsx("td", { className: "border p-2", children: t.brokerage || meta["Brok Amt"] || "-" }), _jsx("td", { className: "border p-2", children: t.net_amount || meta["Net Amt"] || "-" }), _jsx("td", { className: "border p-2", children: t.date || meta["Trd Dt"] || "-" }), _jsx("td", { className: "border p-2", children: t.created_at
                                                ? new Date(t.created_at).toLocaleTimeString()
                                                : "-" })] }, t.id));
                            }) })] }) })] }));
}
